// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kufibqipthrwoclhtmmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1ZmlicWlwdGhyd29jbGh0bW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NzU4MjIsImV4cCI6MjA2NzE1MTgyMn0.zM_voZTlgJ7Swajj4PgeqFGClCdp-vw8GTY52yqQPKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});