// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://munpnfjhjgewqqfzzbga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11bnBuZmpoamdld3FxZnp6YmdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNDcxNzcsImV4cCI6MjA2MzYyMzE3N30.7nCJLL83170ozc0CGBQMYriDMiHYsGx04uIvP2QKFzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);